version: '{build}'
# If changed sync with the command in the install section
image: Visual Studio 2019
platform:
# It is hardcoded 32 won't work
- x64
environment:
  global:
    DISTUTILS_USE_SDK: 1
    MSSdk: 1
    # SSE2 is the default in recent VS, but let's keep for older versions, see, e.g.: https://github.com/weidai11/cryptopp/issues/445
    ARCH: SSE2
  matrix:
  - PYTHON: 37
  - PYTHON: 38
  - PYTHON: 312
  - PYTHON: 310
  - PYTHON: 39
  - PYTHON: 311
  pypipassword:
    # https://ci.appveyor.com/tools/encrypt
    secure: 7hxZ+XinYPLuIS1aHZbTcA==
install:
- cmd: '"c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%'
- cmd: git config core.symlinks true
- cmd: git reset --hard
- cmd: rmdir "C:\cygwin" /s /q
- cmd: rmdir "C:\cygwin64" /s /q
- ps: |
    $env:PYTHON = "$env:PYTHON-x64" 
    $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
    echo $env:PATH
    python -m pip install --disable-pip-version-check --upgrade pip
    python -m pip install -qq setuptools six psutil scikit-learn pytest pytest-runner
- cmd: |
    ECHO Platform : %PLATFORM%
    ECHO Python : %PYTHON%
    ECHO PATH : %PATH%
    set
    python --version
    python -m pip --version
build_script:
- ps: cd python_bindings
- cmd: |
    python -m pip install -qq -r requirements.txt
    python setup.py build_ext
    python -m pip install -U .
- ps: cd ..

test_script:
- ps: cd python_bindings
- cmd: pytest tests
- ps: cd ..

deploy_script: 
- ps: |
    if ($env:APPVEYOR_REPO_TAG -ne "true") {
      echo "Skipping deployment because this is not a tagged commit"
      return
    }
    # Specify account details for PyPI
    echo "Deploying..."
    mv .pypirc $env:USERPROFILE\\.pypirc
    # Workaround required to ensure setup.py finds the .pypirc under Windows
    $env:HOME=$env:USERPROFILE
    # Install wheel-building support
    python -m pip install --user wheel twine
    # Build wheel and upload
    cd python_bindings
    python setup.py build_ext
    python setup.py sdist bdist_wheel
    python -m twine upload -r testpypi -p $env:pypipassword --skip-existing dist/*
    echo "Deployment complete"

