language: cpp
matrix:
  include:
  - os: linux
    env: PYTHON=2.7
  - os: osx
    env: PYTHON=3.6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libblas-dev
    - liblapack-dev
    - gfortran
    - cmake

before_install:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.8 CC=gcc-4.8; fi
  if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "${PYTHON:0:1}" = "3" ]; then
      brew update
      brew install python3
      command curl -sSL https://rvm.io/mpapis.asc | gpg --import -;
      rvm get stable
  fi
  pip install --user --upgrade pip virtualenv
  virtualenv -p python$PYTHON venv
  source venv/bin/activate

install:
  - cmake similarity_search && make -j 4
  - travis_wait travis_retry pip install -r python_bindings/requirements.txt scipy six flake8
  - travis_retry cd python_bindings && python setup.py build install && cd ..

script:
- |
  set -e
  if [ "$TRAVIS_OS_NAME" = "linux" -o "$TRAVIS_OS_NAME" = "osx" ] ; then
      cd similarity_search;
      ./release/bunit
      cd ..
  fi
  cd python_bindings
  python setup.py test
  flake8
  cd ..
cache:
  - apt
  - directories:
    - $HOME/.cache/pip
